CREATE TABLE cliente (
idCliente INT PRIMARY KEY IDENTITY(1,1),
nome VARCHAR(80) NOT NULL,
email VARCHAR(255) NOT NULL,
telefone VARCHAR(20) NOT NULL,
cpf VARCHAR(11) NOT NULL,
dataDeCadastro DATETIME DEFAULT GETDATE(),
ativo TINYINT DEFAULT 1,
);