CREATE TABLE contato (
idContato INT PRIMARY KEY IDENTITY(1,1),
nome VARCHAR(80) NOT NULL,
email VARCHAR(255) NOT NULL,
telefone VARCHAR(20) NULL,
assunto VARCHAR(150) NOT NULL,
mensagem VARCHAR(200) NOT NULL,
idCursos INT NULL,
dataDeCadastro DATETIME DEFAULT GETDATE(),
ativo TINYINT DEFAULT 1,
);